### ISSUE TITLE
Timeout entities in minutes

### ISSUE THREAD

**Issue by jfroy** [bdraco/baf#1]
I'm not sure if this should be done in `aiobafi6` or the integration, but from an ergonomics point of view I think it makes more sense to display the various timeout entities in minutes rather than seconds. The entities probably also should have `unit_of_measurement`.

I've prototyped this in https://github.com/jfroy/baf/commit/23c1e247dc73b96b7661cdda02fcd5542db06c63

**Comment by bdraco** [comment]
I thought about doing that, but since the app allows configuring some of the values in 30s intervals it would prevent home assistant from seeing the precision

**Comment by bdraco** [comment]
I agree we should add UOMs

**Comment by bdraco** [comment]
This is a bit of a frontend issue though.  Ideally we could set the number entity to have a class of duration and the frontend would know what to do

**Comment by jfroy** [comment]
Yeah to some extent a fancy ~~Lovelace~~ dashboard could change the unit, or build an adaptive scale slider, etc. The backend entity reflecting the raw firmware value is not a bad design. It just makes default dashboards somewhat meh.
